const data1 = [
  {
    id: 1,
    name: 'Masculine Mind',
    accountImage: './img/yZawJEcY_400x400.jpg',
    account: '@MasculineMind_',
    date: '8h',
    postArticle: `Don't let hard times break you. Let them shape you. Your hardest times can be the foundation for your greatest successes. Confront the challenges the comes your way and use them to make you stronger.`,
    postImage: '',
    comment: '2',
    retweet: '11',
    likes: '47',
    views: '2,098',
    share: '',
  },
  {
    id: 2,
    name: 'Name cannot be blank',
    accountImage: './img/lpi5wPb4_400x400.jpg',
    account: '@hackSultan',
    date: '3h',
    postArticle: `Techiessssss just RT to mark attendance tonight..... and tell me where you're learning from.`,
    postImage: '',
    comment: '96',
    retweet: '259',
    likes: '317',
    views: '11.8k',
    share: '',
  },
  {
    id: 3,
    name: 'Shashi Lo',
    accountImage: './img/QzFpA28W_400x400.jpg',
    account: '@shashiwhocodes',
    date: '1h',
    postArticle: `If you don't understand something, do not be shy to as for help after you've tried to find a solution. <br /><br /> It's ok not to be ok. Everything will be alright.`,
    postImage: '',
    comment: '1',
    retweet: '8',
    likes: '26',
    views: '644',
    share: '',
  },
  {
    id: 4,
    name: 'LeadDev',
    accountImage: './img/SGBQf3vv_400x400.jpg',
    account: '@TheLeadDev',
    date: '1h',
    postArticle: `The way your team builds software matters. <span class="link">bit.ly/3NkiN8u</span>`,
    postImage: './img/FurabtkWIAAotUv.jpeg',
    comment: '1',
    retweet: '7',
    likes: '26',
    views: '135',
    share: '',
  },
  {
    id: 5,
    name: 'Àgbà Akin',
    accountImage: './img/RhHPvX__400x400.jpg',
    account: '@kynsofficial',
    date: 'Apr 23',
    postArticle: `Elon Musk and Jack didn't sign NON-COMPLETE? because the Bluesky is copycat of Twitter.`,
    postImage: '',
    comment: '64',
    retweet: '176',
    likes: '1653',
    views: '190.3k',
    share: '',
  },
  {
    id: 6,
    name: 'Shreya Trivedi',
    accountImage: './img/fNLdhnnQ_400x400.jpg',
    account: '@_Shreya_Trivedi',
    date: '21h',
    postArticle: `Reminder! <br /><br /> Learn javascript before React`,
    postImage: '',
    comment: '94',
    retweet: '92',
    likes: '768',
    views: '61.9k',
    share: '',
  },
  {
    id: 7,
    name: 'Madza👨‍💻⚡',
    accountImage: './img/w25QtNnl_400x400.jpg',
    account: '@madzadev',
    date: '11h',
    postArticle: `The lazy attribute specifies whether a browser should load an image immediately or to defer loading of off-screen images until, for example, the user scrolls near them ✨`,
    postImage: './img/FupXhjEWYAI1gTt.jpeg',
    comment: '4',
    retweet: '28',
    likes: '179',
    views: '13k',
    share: '',
  },
];

const data2 = [
  {
    id: 1,
    name: 'Ajay Sharma',
    accountImage: './img/ZBKrWlkw_400x400.jpg',
    account: '@ajaysharma_here',
    date: '15h',
    postArticle: `Javascript Function bind () 👇`,
    postImage: './img/FuodeggXgAE1t1g.jpeg',
    comment: '5',
    retweet: '23',
    likes: '88',
    views: '5,991',
    share: '',
  },
  {
    id: 2,
    name: 'Namya',
    accountImage: './img/tx_TaL7Q_400x400.jpg',
    account: '@namyakhann',
    date: '19h',
    postArticle: `Javascript rules the Coding world! <br /><br /> Here's 10 Javascript libraries you can't afford to miss:`,
    postImage: './img/Funm7vEWcAUeR84.jpeg',
    comment: '13',
    retweet: '184',
    likes: '816',
    views: '50.4k',
    share: '',
  },
  {
    id: 3,
    name: 'UEFA Champions League',
    accountImage: './img/Jc9RL5o7_400x400.jpg',
    account: '@ChampionsLeague',
    date: '10h',
    postArticle: ``,
    postImage: './img/Fuo561lWIAE_sB5.jpeg',
    comment: '388',
    retweet: '2585',
    likes: '33.4k',
    views: '1.3M',
    share: '',
  },
];

const trends = [
  {
    id: 1,
    category: 'Trending',
    trend: 'NYSC',
    tweets: '1,608 tweets',
  },
  {
    id: 2,
    category: 'Technology • Trending',
    trend: '#opensource',
    tweets: '3,848 Tweets',
  },
  {
    id: 3,
    category: 'Trending in Nigeria',
    trend: 'Daniel',
    tweets: '196k tweets',
  },
  {
    id: 4,
    category: 'Trending in Nigeria',
    trend: 'Imagination',
    tweets: '30k tweets',
  },
  {
    id: 5,
    category: 'Trending in Nigeria',
    trend: 'Opay',
    tweets: '20.5k tweets',
  },

  {
    id: 6,
    category: 'Trending in Nigeria',
    trend: 'Bola Ahmed Tinubu',
    tweets: '23.7k tweets',
  },
  {
    id: 7,
    category: 'Trending',
    trend: 'Spineless',
    tweets: '12k tweets',
  },
  {
    id: 8,
    category: 'Only on Twitter • Trending',
    trend: 'Little Rock',
    tweets: '65.1k tweets',
  },
  {
    id: 9,
    category: 'Technology • Trending',
    trend: '50 HTML',
    tweets: '16.4K tweets',
  },
];

export { data1, data2, trends };
